[build]
  command = "npm run build:netlify"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Disable automatic Next.js plugin to avoid conflicts
[[plugins]]
  package = "@netlify/plugin-nextjs"
  enabled = false

# Ensure clean builds
[build.processing]
  skip_processing = false
